--Inicio de repositorio

USE master
GO

IF EXISTS(SELECT * FROM sys.databases WHERE NAME = 'lmsDB')
	BEGIN
		DROP DATABASE lmsDB
	END
GO

CREATE DATABASE lmsDB
GO

USE lmsDB
GO

CREATE SCHEMA GestionRolesPermisos
GO

CREATE SCHEMA GestionIdentidadAcad
GO

CREATE SCHEMA GestionTutores
GO

CREATE SCHEMA GestionEventosSesiones
GO

-- Tabla 3.1 HORARIOS_TUTOR

CREATE TABLE HORARIOS_TUTOR (
    id_horario INT IDENTITY(1,1) PRIMARY KEY,
    id_tutor INT NOT NULL,
    horario TIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_HORARIOS_TUTOR_TUTORES
        FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor)
)
GO


-- Tabla 3.2 TUTOR_MATERIA

CREATE TABLE TUTOR_MATERIA (
    id_tutor_materia INT IDENTITY(1,1) PRIMARY KEY,
    id_tutor INT NOT NULL,
    id_mat INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_TUTOR_MATERIA_TUTORES
        FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor),

    CONSTRAINT FK_TUTOR_MATERIA_MATERIAS
        FOREIGN KEY (id_mat) REFERENCES MATERIAS(id_mat),

    CONSTRAINT UQ_TUTOR_MATERIA
        UNIQUE (id_tutor, id_mat)
)
GO


-- Tabla 3.3 TUTORES_VALIDACION

CREATE TABLE TUTORES_VALIDACION (
    id_validacion INT IDENTITY(1,1) PRIMARY KEY,
    id_tutor INT NOT NULL,
    is_valid BIT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_TUTORES_VALIDACION_TUTORES
        FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor),

    CONSTRAINT UQ_TUTORES_VALIDACION
        UNIQUE (id_tutor)
)
GO


-- Tabla 3.4 ACREDITACIONES

CREATE TABLE ACREDITACIONES (
    id_acreditacion INT IDENTITY(1,1) PRIMARY KEY,
    id_tutor INT NOT NULL,
    archivo VARBINARY(MAX) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_ACREDITACIONES_TUTORES
        FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor)
)
GO


-- Tabla 3.5 PERFIL_TUTOR

CREATE TABLE PERFIL_TUTOR (
    id_perfil_tutor INT IDENTITY(1,1) PRIMARY KEY,
    id_tutor INT NOT NULL,
    descripcion NVARCHAR(MAX) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_PERFIL_TUTOR_TUTORES
        FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor),

    CONSTRAINT UQ_PERFIL_TUTOR
        UNIQUE (id_tutor)
)
GO


-- Tabla 3.6 CALIFICACIONES_TUTOR

CREATE TABLE CALIFICACIONES_TUTOR (
    id_calificacion INT IDENTITY(1,1) PRIMARY KEY,
    id_tutor INT NOT NULL,
    puntuacion DECIMAL(3,1) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_CALIFICACIONES_TUTOR_TUTORES
        FOREIGN KEY (id_tutor) REFERENCES TUTORES(id_tutor),

    CONSTRAINT CK_CALIFICACIONES_TUTOR_PUNTUACION
        CHECK (puntuacion BETWEEN 0 AND 5)
)
GO


-- Tabla 3.7 METRICAS_APRENDIZAJE

CREATE TABLE METRICAS_APRENDIZAJE (
    id_metrica INT IDENTITY(1,1) PRIMARY KEY,
    periodo NVARCHAR(50) NOT NULL,
    id_mat INT NOT NULL,
    estado_sesion NVARCHAR(100) NOT NULL,
    total_inscritos INT NOT NULL DEFAULT 0,
    total_asistencias INT NOT NULL DEFAULT 0,
    promedio_puntuacion DECIMAL(3,1) NULL,
    created_at DATETIME NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME NULL,

    CONSTRAINT FK_METRICAS_APRENDIZAJE_MATERIAS
        FOREIGN KEY (id_mat) REFERENCES MATERIAS(id_mat),

    CONSTRAINT CK_METRICAS_TOTAL_INSCRITOS
        CHECK (total_inscritos >= 0),

    CONSTRAINT CK_METRICAS_TOTAL_ASISTENCIAS
        CHECK (total_asistencias >= 0),

    CONSTRAINT CK_METRICAS_PROMEDIO
        CHECK (promedio_puntuacion IS NULL OR promedio_puntuacion BETWEEN 0 AND 5)
)
GO